language: python
python:
- '3.6'
script:
- export LANG=en_US.UTF-8
- wget https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo apt-get install python3.4-venv
- export PATH=.:$PATH
- wget https://bootstrap.pypa.io/get-pip.py
- python3.4 -m venv rune3
- . rune3/bin/activate
- cp chromedriver rune3/bin
- echo $PATH
- ls rune3/bin
- ./rune3/bin/python -m ensurepip
- ./rune3/bin/python get-pip.py
- ./rune3/bin/pip install -e .
- ./rune3/bin/pip install -r requirements.txt
- ./rune3/bin/pip install pyvirtualdisplay
- "./runTests.sh"
notifications:
  slack:
    secure: OfeZ/+YHpSl7GNFkzEKu0uObuMdymKmDEeDyfB++RaglalcgkDQAqrCPx+YVw6brXOHGeC6BkGJe/Fs143Ai8/yf38nMmZg/dej5nLgZNST67jWaapIydx5QeuCrsRKvUP+z6yEYoBkYXTsYPyTiKGGsyzvX6dimZRT4nD8qrv0=