language: python
python:
- '3.7'
script:
- export LANG=en_US.UTF-8
- wget https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo apt-get install python3.4-venv
- sudo apt-get -y update
- sudo apt-get -y install google-chrome-stable
- export PATH=.:$PATH
- wget https://bootstrap.pypa.io/get-pip.py
- python3.7 -m venv rune3
- ". rune3/bin/activate"
- cp chromedriver rune3/bin
- echo $PATH
- ls rune3/bin
- "./rune3/bin/python -m ensurepip"
- "./rune3/bin/python get-pip.py"
- "./rune3/bin/pip install -e ."
- "./rune3/bin/pip install -r requirements.txt"
- "./rune3/bin/pip install pyvirtualdisplay"
- "./runTests.sh"
notifications:
  slack:
    secure: ZM7WB8p85i+sZXQYqlm7M/Eu1ZL5UptFw3ZRpzWuBMnC/OLw721eGaY1GsbyLhqtBUMbMnaStwptz/mHEZfEv36ARSnyOZdhl+g5ckQKUB+ECULk7HkyjiU4kPJ5U/yyGUFBZUFlZfhY76EBOqtGU6IhXw8TqWOfD8CZDXXvICE=
