# *********
# |docname|
# *********
dist: xenial
language: python
python:
- '3.7'
- '3.8'
node_js: "13.8"
install: "npm install"

script:
- export LANG=en_US.UTF-8
- wget https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo apt-get -y update
- sudo apt-get -y install google-chrome-stable
- export PATH=$TRAVIS_BUILD_DIR:$PATH
- "python -m pip install -U pip"
- "pip install -e ."
- "pip install -U -r requirements-dev.txt"
- "pytest"
notifications:
  slack: runestoneteam:aKSajF6qfp9WpgisFH8mocs6
